from enum import StrEnum


class LotStatus(StrEnum):
    DRAFT = "DRAFT"
    CAPTURED = "CAPTURED"
    VERIFYING = "VERIFYING"
    VERIFIED = "VERIFIED"
    LISTED = "LISTED"
    OFFERS_RECEIVED = "OFFERS_RECEIVED"
    OFFER_ACCEPTED = "OFFER_ACCEPTED"
    HANDOVER_SCHEDULED = "HANDOVER_SCHEDULED"
    PICKED_UP = "PICKED_UP"
    IN_TRANSIT = "IN_TRANSIT"
    RECEIVED = "RECEIVED"
    WEIGHT_VERIFIED = "WEIGHT_VERIFIED"
    PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED"
    PROCESSING = "PROCESSING"
    RECYCLING_EVIDENCE_ADDED = "RECYCLING_EVIDENCE_ADDED"
    CLOSED = "CLOSED"
    FLAGGED = "FLAGGED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    DISPUTED = "DISPUTED"